"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# settings.py 위치 기준으로 BASE_DIR 확정
BASE_DIR = Path(__file__).resolve().parent.parent

# backend/config/.env 로드
load_dotenv(BASE_DIR / ".env")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$5%zg45x2w$v&^roxh=*%3n7(n%d9lm&=gmto*02*w#5(l%%qt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'i14b209.p.ssafy.io',  # 실제 도메인 추가
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    # JWT
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # DB 저장/무효화(blacklist)

    # local_apps
    "local_apps.users",
    "local_apps.oauth_accounts",
    "local_apps.tokens",
    "local_apps.boards",
    "local_apps.channels",
    "local_apps.user_info",
    "local_apps.search_logs",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# react 개발 서버 origin 허용
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://i14b209.p.ssafy.io",
]
CORS_ALLOW_CREDENTIALS = True

# 로컬 개발용 cookie 설정
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# DRF 인증 클래스 설정
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # 일단 전역은 AllowAny로 두고, 보호할 API에만 IsAuthenticated 적용
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

# SimpleJWT 헤더 타입(Bearer) 설정
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # ACCESS 토큰 유지 시간(선택 가능)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),  # REFRESH 토큰 유지 기간(선택 가능)
    # refresh 토큰 회전/블랙리스트 처리로 refresh 재사용 방지 + 서버 무효화
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # 헤더 규칙 고정  무엇: Bearer 타입만 허용
    "AUTH_HEADER_TYPES": ("Bearer",),
    # User 모델의 PK가 user_id이므로 명시적으로 지정
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
}

# Refresh 쿠키 정책
REFRESH_COOKIE_NAME = "refresh"
REFRESH_COOKIE_HTTPONLY = True
REFRESH_COOKIE_SAMESITE = "Lax" # 다른 사이트에서 발생한 요청해 쿠키를 보낼지 여부
REFRESH_COOKIE_SECURE = False   # True면 HTTPS(배포) 요청에서만 쿠키가 전송됨
REFRESH_COOKIE_MAX_AGE = 60 * 60 * 24 * 14  # 쿠키 수명(초 단위)

AUTH_USER_MODEL = "users.User"

# ===== Mattermost REST API 설정 =====
MATTERMOST_BASE_URL = os.getenv("MM_BASE_URL", "https://meeting.ssafy.com")