# Generated by Django 5.2.10 on 2026-01-30 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "calendar_event_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "custom_title",
                    models.CharField(db_column="custom_title", max_length=200),
                ),
                (
                    "custom_content",
                    models.TextField(blank=True, db_column="custom_content", null=True),
                ),
                ("custom_start_at", models.DateTimeField(db_column="custom_start_at")),
                ("custom_end_at", models.DateTimeField(db_column="custom_end_at")),
                (
                    "mm_link",
                    models.CharField(
                        blank=True, db_column="mm_link", max_length=200, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=10, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "calendar_event",
                "ordering": ["custom_start_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_calendar_user"),
                    models.Index(fields=["custom_start_at"], name="idx_calendar_start"),
                ],
            },
        ),
    ]
