# Generated by Django 5.2.10 on 2026-02-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="board_name",
            field=models.CharField(
                blank=True, db_column="board_name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="channel_name",
            field=models.CharField(
                blank=True, db_column="channel_name", max_length=100, null=True
            ),
        ),
    ]
