# Generated by Django 5.2.10 on 2026-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0002_calendarevent_board_name_calendarevent_channel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="custom_content",
            field=models.CharField(
                blank=True, db_column="custom_content", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="custom_title",
            field=models.CharField(db_column="custom_title", max_length=50),
        ),
    ]
