# Generated by Django 5.2.10 on 2026-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "board_id",
                    models.BigAutoField(
                        db_column="board_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "board_name",
                    models.CharField(
                        db_column="board_name", max_length=100, unique=True
                    ),
                ),
                (
                    "mm_team_id",
                    models.CharField(
                        blank=True,
                        db_column="mm_team_id",
                        max_length=26,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "board",
            },
        ),
    ]
