# Generated by Django 5.2.10 on 2026-01-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_name",
            field=models.CharField(db_column="board_name", max_length=100),
        ),
    ]
