# Generated by Django 5.2.10 on 2026-01-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_alter_board_board_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="mm_board_id",
            field=models.CharField(
                blank=True, db_column="mm_board_id", max_length=100, null=True
            ),
        ),
    ]
