version: '3.8'

services:
  # 1. 백엔드 (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ssoc-backend
    restart: always
    ports:
      - "18000:8000"
    environment:
      SECRET_KEY: "django-insecure-secret-key-for-dev"
      DEBUG: "True"
      DB_HOST: "ssafy_db"
      AI_SERVICE_URL: "http://data-webhook:8001" # 필요 시 참조
    networks:
      - ssoc-network

  # 2. 프론트엔드 (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ssoc-frontend
    restart: always
    ports:
      - "15173:5173"
    environment:
      VITE_API_URL: https://i14b209.p.ssafy.io/api
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    networks:
      - ssoc-network

  # 3. 데이터 수집기
  data-webhook:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: ssoc-data-webhook
    restart: always
    env_file:
      - ./AI/.env
    ports:
      - "18001:8001" # Dockerfile의 EXPOSE 8001 포트와 연결
    networks:
      - ssoc-network

  # 4. AI 분석 파이프라인
  ai-pipeline:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: ssoc-ai-pipeline
    restart: always
    env_file:
      - ./AI/.env
    command: python db_pipeline.py
    environment:
      - PYTHONUNBUFFERED=1 # 실시간 로그 출력
    networks:
      - ssoc-network

networks:
  ssoc-network:
    external: true