# Generated by Django 5.2.10 on 2026-01-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "oauth_account_id",
                    models.BigAutoField(
                        db_column="oauth_account_id", primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("provider_uid", models.CharField(max_length=100)),
                ("extra_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_account",
            },
        ),
    ]
