# Generated by Django 5.2.10 on 2026-01-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0002_alter_channel_channel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(db_column="category_name", max_length=50),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        db_column="channel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "db_table": "category",
                "indexes": [
                    models.Index(fields=["channel"], name="idx_category_channel"),
                    models.Index(fields=["category_name"], name="idx_category_name"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "category_name"),
                        name="uniq_category_channel_name",
                    )
                ],
            },
        ),
    ]
