# Generated by Django 5.2.10 on 2026-01-29 04:56

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True, db_column="embedding_vector", dimensions=1536, null=True
            ),
        ),
    ]
