# Generated by Django 5.2.10 on 2026-01-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("channels", "0002_alter_channel_channel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ai_title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("posted_at", models.DateTimeField()),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="categories.category",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        db_column="channel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "db_table": "post",
                "indexes": [
                    models.Index(fields=["channel"], name="idx_post_channel"),
                    models.Index(fields=["category"], name="idx_post_category"),
                    models.Index(fields=["posted_at"], name="idx_post_posted_at"),
                ],
            },
        ),
    ]
