# Generated by Django 5.2.10 on 2026-01-29 05:13

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="벡터 임베딩 (의미 기반 검색용, 1536차원)",
                null=True,
            ),
        ),
    ]
