# Generated by Django 5.2.10 on 2026-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_embedding_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="display_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
