# Generated by Django 5.2.10 on 2026-01-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_display_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mm_post_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
