# Generated by Django 5.2.10 on 2026-01-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "channel_id",
                    models.BigAutoField(
                        db_column="channel_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        db_column="channel_name", max_length=100, unique=True
                    ),
                ),
                (
                    "mm_channel_id",
                    models.CharField(
                        db_column="mm_channel_id", max_length=26, unique=True
                    ),
                ),
                (
                    "mm_channel_type",
                    models.CharField(
                        db_column="mm_channel_type", default="O", max_length=1
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        db_column="board_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="boards.board",
                    ),
                ),
            ],
            options={
                "db_table": "channel",
            },
        ),
    ]
