# Generated by Django 5.2.10 on 2026-01-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0002_alter_channel_channel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostRaw",
            fields=[
                ("post_raw_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author_username", models.CharField(max_length=100)),
                ("mm_post_id", models.CharField(db_index=True, max_length=100)),
                ("raw_content", models.TextField()),
                ("posted_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
                (
                    "channel",
                    models.ForeignKey(
                        db_column="channel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_raws",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Raw",
                "verbose_name_plural": "Post Raws",
                "db_table": "post_raw",
                "indexes": [
                    models.Index(fields=["channel"], name="idx_post_raw_channel"),
                    models.Index(fields=["mm_post_id"], name="idx_post_raw_mm_post_id"),
                ],
            },
        ),
    ]
