# Generated by Django 5.2.10 on 2026-01-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_raws", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postraw",
            name="is_processed",
            field=models.BooleanField(db_column="is_processed", default=False),
        ),
    ]
