# Generated by Django 5.2.10 on 2026-01-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "search_log_id",
                    models.BigAutoField(
                        db_column="search_log_id", primary_key=True, serialize=False
                    ),
                ),
                ("keyword", models.CharField(db_column="keyword", max_length=255)),
                (
                    "filters",
                    models.JSONField(blank=True, db_column="filters", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
