# Generated by Django 5.2.10 on 2026-01-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_logs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchlog",
            name="filters",
        ),
    ]
