# Generated by Django 5.2.10 on 2026-01-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user_channel_id",
                    models.BigAutoField(
                        db_column="user_channel_id", primary_key=True, serialize=False
                    ),
                ),
                ("status", models.BooleanField(db_column="status", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        db_column="channel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_users",
                        to="channels.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_info",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel"), name="unique_user_channel"
                    )
                ],
            },
        ),
    ]
