# Generated by Django 5.2.10 on 2026-01-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0003_post_display_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "archive_id",
                    models.BigAutoField(
                        help_text="아카이브 고유 ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일자"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="공지 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "아카이브",
                "verbose_name_plural": "아카이브 목록",
                "db_table": "archive",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "post"), name="unique_user_archive_post"
                    )
                ],
            },
        ),
    ]
